"""Initial migration

Revision ID: 7fc290cc2f5b
Revises: 8469f6986aad
Create Date: 2025-03-29 21:39:58.920397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc290cc2f5b'
down_revision = '8469f6986aad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
